### ISSUE TITLE
Webhook not responding

### ISSUE THREAD

**Issue by mikececco** [bot-base/telegram-bot-template#461] opened 2024-05-14 11:22 UTC
I cloned repo, set up the basics, sending a request to telegram bot like /start, request is captured from webhook but not responding.
![image](https://github.com/bot-base/telegram-bot-template/assets/88579001/d3db6dfe-5de7-497d-a902-5ac58b4cdeaf)

I am expecting it to respond as stated here: 
```
feature.command("start", logHandle("command-start"), (ctx) => {
  return ctx.reply(ctx.t("welcome"));
});
```
All env keys are set:
BOT_MODE=webhook
BOT_TOKEN=...

I also tried to change NODE_ENV to production and run it with npm start but same behaviour

**Comment by deptyped** [comment] 2024-05-14 12:44
Hi. You need to use the path `/YOUR_BOT_TOKEN` for the webhook, if you haven't changed the path [here](https://github.com/bot-base/telegram-bot-template/blob/679ab0a73c9a4b42a1f47ff7326a765ff6748565/src/server/index.ts#L19).

**Comment by mikececco** [comment] 2024-05-14 12:54
I did change it already(sorry I did not attach it on top post)
  server.post("/webhook", webhookCallback(bot, "fastify"));
When I respond with something like () => ({ status: true }) it works. So Im investigating on whether the webhookCallback has issues

**Comment by mikececco** [comment] 2024-05-14 13:18
I think it does not matter as long as webhook url finishes with /webhook...no?

**Comment by mikececco** [comment] 2024-05-14 13:29
> What did you set in `BOT_WEBHOOK`? It should be something like `https://vocal-sensible-hippo.ngrok-free.app/YOUR_BOT_TOKEN` or `https://vocal-sensible-hippo.ngrok-free.app/webhook` (if you changed the path [here](https://github.com/bot-base/telegram-bot-template/blob/679ab0a73c9a4b42a1f47ff7326a765ff6748565/src/server/index.ts#L19) to `/webhook`)

The second one:
```
{
"ok": true,
["result"](https://api.telegram.org/bot6005475471:AAE_RUqoKcfc0qGXf4L_C7oiqfsaRil_Ibg/getWebhookInfo): {
"url": ["https://vocal-sensible-hippo.ngrok-free.app/webhook"](https://vocal-sensible-hippo.ngrok-free.app/webhook),
"has_custom_certificate": false,
"pending_update_count": 2,
"last_error_date": 1715690786,
"last_error_message": "Wrong response from the webhook: 503 Service Unavailable",
"max_connections": 40,
"ip_address": "3.125.102.39",
["allowed_updates"](https://api.telegram.org/bot6005475471:AAE_RUqoKcfc0qGXf4L_C7oiqfsaRil_Ibg/getWebhookInfo): [
"message",
"callback_query"
]
}
}
```

**Comment by deptyped** [comment] 2024-05-14 13:37
> Wrong response from the webhook: 404 Not Found

Looks like the `/webhook` path doesn't exist for some reason?

**Comment by deptyped** [comment] 2024-05-14 13:40
(Also, please revoke your bot token using https://t.me/BotFather, it's leaked in edit history)

**Comment by mikececco** [comment] 2024-05-14 13:42
> > Wrong response from the webhook: 404 Not Found
> 
> Looks like the `/webhook` path doesn't exist for some reason?

Webhook endpoint exists, if I return like:   `server.post("/endpoint", () => ({ status: true }));` it works

**Comment by deptyped** [comment] 2024-05-14 13:46
> if I return like: `server.post("/endpoint", () => ({ status: true }));` it works

Are you checking through ngrok or using 127.0.0.1? Maybe some tunneling issue?

**Comment by mikececco** [comment] 2024-05-14 14:02
> > if I return like: `server.post("/endpoint", () => ({ status: true }));` it works
> 
> Are you checking through ngrok or using 127.0.0.1? Maybe some tunneling issue?
Through ngrok. I am also getting `Error occurred: HttpError: Network request for 'setWebhook' failed!` if I dont comment that code. Might be something related to bot instance?

**Comment by deptyped** [comment] 2024-05-14 14:25
> Error occurred: HttpError: Network request for 'setWebhook' failed!

You can enable sensitive logs to see why it happens. Change this line:
https://github.com/bot-base/telegram-bot-template/blob/679ab0a73c9a4b42a1f47ff7326a765ff6748565/src/main.ts#L10
to 
```ts
const bot = createBot(config.BOT_TOKEN, {
  config: {
    client: {
      sensitiveLogs: true,
    },
  },
});
```

**Comment by mikececco** [comment] 2024-05-14 14:32
> > Error occurred: HttpError: Network request for 'setWebhook' failed!
> 
> You can enable sensitive logs to see why it happens. Change this line:
> 
> https://github.com/bot-base/telegram-bot-template/blob/679ab0a73c9a4b42a1f47ff7326a765ff6748565/src/main.ts#L10
> 
> 
> to
> ```ts
> const bot = createBot(config.BOT_TOKEN, {
>   config: {
>     client: {
>       sensitiveLogs: true,
>     },
>   },
> });
> ```

Apparently it is setting it to be empty to be empty:
```
{
"ok": true,
"result": true,
"description": "Webhook is already deleted"
}
```
But that is not a problem now as I set it up manually

**Comment by mikececco** [comment] 2024-05-14 15:21
Are we also sure fastify middleware works?

**Comment by deptyped** [comment] 2024-05-14 16:08
> Are we also sure fastify middleware works @deptyped ?

Hmm, I can confirm that something is broken.
It seems to be related to [this change](https://github.com/grammyjs/grammY/commit/d18637f711a11026d1612791d9f518536b4ac88c) in grammY. Reverting it fixes the problem.

**Comment by deptyped** [comment] 2024-05-14 16:48
> How can I revert it on my end?

The simplest way is to manually revert the changes to the `node_modules/grammy/out/convenience/frameworks.js` file. Fastify-related code is near 116 line.

**Comment by mikececco** [comment] 2024-05-14 17:05
I did change it:
```
const fastify = (req, reply) => ({
    update: Promise.resolve(req.body),
    header: req.headers[SECRET_HEADER_LOWERCASE],
    end: () => reply.status(200).send(),
    respond: (json) => reply.send(json),
    unauthorized: () => reply.code(401).send(WRONG_TOKEN_ERROR),
});
```

but still my request comes in, I'm sending /start and no response back:
```
[19:03:44.302] INFO: incoming request
    reqId: "req-3"
    req: {
      "method": "POST",
      "url": "/webhook",
      "hostname": "vocal-sensible-hippo.ngrok-free.app",
      "remoteAddress": "127.0.0.1",
      "remotePort": 46724
    }

```

**Comment by mikececco** [comment] 2024-05-15 09:03
Any idea?

**Comment by deptyped** [comment] 2024-05-15 09:12
I replaced Fastify with [Hono](https://hono.dev/) in the template. If Fastify is not a requirement for you, you can fetch the latest changes to use Hono instead.

**Comment by mikececco** [comment] 2024-05-15 09:27
> I replaced Fastify with [Hono](https://hono.dev/) in the template. If Fastify is not a requirement for you, you can fetch the latest changes to use Hono instead.

How can I do that? (junior developer here)

**Comment by deptyped** [comment] 2024-05-15 09:49
> How can I do that? (junior developer here)

If you generated a new repository, you need to add the template repository as a remote:
```
git remote add template git@github.com:bot-base/telegram-bot-template.git
git remote update
```
And then merge the changes from `main` branch:
```
git merge template/main --squash --no-commit --allow-unrelated-histories
```

If you just cloned this repository, you need to pull the changes:
```sh
git pull origin main
```

**Comment by mikececco** [comment] 2024-05-15 10:06
Thank you!

**Comment by mikececco** [comment] 2024-05-15 11:43
@deptyped still not working  Webhook not responding to /start message
```
[13:40:32.972] INFO: Webhook was set
    url: "https://vocal-sensible-hippo.ngrok-free.app/webhook"
[13:40:32.975] INFO: Server started
    url: "http://127.0.0.1:3000"
[13:41:53.379] DEBUG: Incoming request
    requestId: "a02e21d2-6df4-4409-afde-7136c093d9cd"
    method: "POST"
    path: "/webhook"

```

**Comment by deptyped** [comment] 2024-05-15 12:16
Hm, according to the logs everything is ok, the request is received on the webhook and passed to the handler. I can't reproduce the problem either. Can you please share the code or provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by mikececco** [comment] 2024-05-15 12:32
@deptyped 
I cloned the repo again, I had to remove the following code:
```
    // await bot.init(); --> this


    // start server
    serve(
      {
        fetch: server.fetch,
        hostname: config.BOT_SERVER_HOST,
        port: config.BOT_SERVER_PORT,
      },
      (info) => {
        const url =
          info.family === "IPv6"
            ? `http://[${info.address}]:${info.port}`
            : `http://${info.address}:${info.port}`;

        logger.info({
          msg: "Server started",
          url,
        });
      },
    );

    // set webhook --> AND THIS
    // await bot.api.setWebhook(config.BOT_WEBHOOK, {
    //   allowed_updates: config.BOT_ALLOWED_UPDATES,
    //   secret_token: config.BOT_WEBHOOK_SECRET,
    // });
```

but besides that npm run dev accepts requests, but still not working. I am using ngrok, on which I set the /webhook endpoint. Didnt change anything else besides that.

**Comment by mikececco** [comment] 2024-05-15 14:03
Yes I can confirm there is something with the middleware

**Comment by deptyped** [comment] 2024-05-15 14:04
> I had to remove the following code

Why? `await bot.init()` is necessary to ensure that your bot token is correct before you start receiving requests from Telegram. If it doesn't work, it means your bot won't work either.

**Comment by mikececco** [comment] 2024-05-15 14:04
> > I had to remove the following code
> 
> Why? `await bot.init()` is necessary to ensure that your bot token is correct before you start receiving requests from Telegram. If it doesn't work, it means your bot won't work either.

Any suggestion on that? Its a simple bot

**Comment by mikececco** [comment] 2024-05-15 14:07
I created a new bot with new token but same issue... bot.init() is pending

**Comment by deptyped** [comment] 2024-05-15 15:17
> I created a new bot with new token but same issue... bot.init() is pending

That's weird. Can you access Bot API directly?
```
https://api.telegram.org/botTOKEN/getMe
```

> from grammy documentation, is it the case in which we need to init automatically?

I sometimes encountered [this error](https://github.com/grammyjs/grammY/blob/main/src/bot.ts#L248-L250) without manual initialization. Probably automatic initialization doesn't work well enough if the bot receives many requests immediately after startup. However, this was about a year ago, maybe it's fixed now.

But there's another reason to initialize manually. If we have incorrect credentials, what's the point of starting the server, fetching an update, and halting operations in the middle of processing due to an incorrect token? It's much better to fail fast.

**Comment by mikececco** [comment] 2024-05-15 15:17
if (
    // !process.env.IS_BROWSER && // uncomment this line if you use a bundler that sets env.IS_BROWSER during build time
    process.versions &&
    // check for `node` in case we want to use this in "exotic" JS envs
    process.versions.node
  ) {
    setDefaultAutoSelectFamily(false);
  }
  
  this piece of code fixed it.
  It has somethind to do with IPv6 / IPv4

**Comment by deptyped** [comment] 2024-05-15 15:22
> It has somethind to do with IPv6 / IPv4

Wow 🤯  
I'm glad you found a solution! So, does everything work now?

**Comment by mikececco** [comment] 2024-05-16 00:28
Everything works now!

**Comment by mikececco** [comment] 2024-05-17 15:06
It is not working in production though

**Comment by deptyped** [comment] 2024-05-17 22:03
Make sure you turn off [Vercel Authentication](https://vercel.com/docs/security/deployment-protection/methods-to-protect-deployments/vercel-authentication#manage-using-the-dashboard) and set the `NODEJS_HELPERS` environment variable to `0`

**Comment by mikececco** [comment] 2024-05-18 01:06
Nothing to do, all endpoints work but Webhookcallback is not being called.
I did not add anything besides cloning the repo and deploying it to vercel
and configuring env variables. I wonder if it has something to do with IPv4
again

**Comment by mikececco** [comment] 2024-05-18 01:14
Vercel dev works perfectly locally though.

**Comment by deptyped** [comment] 2024-05-18 19:46
Try `getWebhookInfo` method to check if there is any error
`https://api.telegram.org/botTOKEN/getWebhookInfo`

**Comment by mikececco** [comment] 2024-05-19 01:54
Did solve it, by changing to polling once and switching back to webhook
mode. Don't ask me why.

**Closed** 2024-08-04 09:44 UTC
